# SPDX-FileCopyrightText: © 2024 Kosta Vukicevic (stcksmsh)
# SPDX-FileCopyrightText: © 2024 Christian Buhtz <c.buhtz@posteo.jp>
#
# SPDX-License-Identifier: CC0-1.0
#
# This file is released under Creative Commons Zero 1.0 (CC0-1.0) and part of
# the program "Back In Time". The program as a whole is released under GNU
# General Public License v2 or any later version (GPL-2.0-or-later).
# See file/folder LICENSE or
# go to <https://spdx.org/licenses/CC0-1.0.html>
# and <https://spdx.org/licenses/GPL-2.0-or-later.html>.

# Project information
site_name: Back In Time - User Manual
site_author: Back In Time Team

# Source files (markdown)
docs_dir: src

# Output directory
site_dir: html

# Needed to use local generated docu if browser won't open index.html files in
# sub directories. See https://github.com/mkdocs/mkdocs/discussions/3847
use_directory_urls: false

# site_url: https://backintime-docs.readthedocs.io/en/latest/
# site_description: Back In Time is a simple backup tool for Linux inspired by "FlyBack".

# Repository information
repo_name: backintime
# repo_url: https://github.com/bit-team/backintime

# Entrie labels determined by the the 1st level heading
nav: 
  - 'index.md'
  - 'quick-start.md'
  - 'main-window.md'
  - 'settings.md'
  - 'snapshots-dialog.md'
  - 'log.md'
  - 'user-callback.md'
  - 'additional.md'

markdown_extensions:
  # Boxex for warnings, etc.
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - toc:
      permalink: true  
  - footnotes
  # Syntax highlightening in code blocks
  - pymdownx.highlight:
      linenums: true
      # clickable and referencable lines numbers
      anchor_linenums: true
      # Highlight (and reference) a bunch of lines
      line_spans: __span
      # Somehow ease up CSS stuff
      pygments_lang_class: true
  # No line numbers without it. Don't understand why.
  - pymdownx.superfences

# Configuration
theme:
    name: material
    logo: _images/logo48.png
    favicon: _images/logo48.png
    language: en
    features:
      # Load content of main page only instead of the whole site
      - navigation.instant
      # Loading in background while hovering over the navigation item
      - navigation.instant.prefetch
      # Unfold all entries in navigation side bar
      - navigation.expand
      # Render navigation path on above the title of each page
      - navigation.path
      # Back-to-top-button
      - navigation.top
      # Render sub-headings in navigation side bar
      - toc.integrate
      - toc.follow
      # Highlight search results
      - search.highlight
      # Footer
      # - navigation.footer
      # Link current document to Microsoft GitHub
      - content.action.edit
      - content.action.view
      # Copy and highlight code blocks
      - content.code.copy
      - content.code.select
    # Colorsettings regarding dark/light mode
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@backintime
      name: Back In Time in the Fediverse on Mastodon as @backintime@fosstodon.org
    - icon: fontawesome/brands/github
      link: https://github.com/bit-team/backintime
      name: Source code repository at Microsoft GitHub

copyright: © Back In Time Team 